FROM pytorch/pytorch:1.10.0-cuda11.3-cudnn8-devel

RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y

RUN mkdir -p ./app
COPY checkpoints_G_markerpen/last_ckpt.pt ./app/checkpoints_G_markerpen/last_ckpt.pt
COPY checkpoints_G_oilpaintbrush/last_ckpt.pt ./app/checkpoints_G_oilpaintbrush/last_ckpt.pt
COPY checkpoints_G_rectangle/last_ckpt.pt ./app/checkpoints_G_rectangle/last_ckpt.pt
COPY checkpoints_G_watercolor/last_ckpt.pt ./app/checkpoints_G_watercolor/last_ckpt.pt
 